-- Execute this script in the Supabase SQL Editor to fix visibility and duplication issues.

-- 1. Ensure the table exists with the correct structure (in case it was partially created)
-- Note: The screenshot shows specific casing and types.
CREATE TABLE IF NOT EXISTS public.open_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo TEXT,
    conta TEXT,
    preco_medio TEXT,
    cliente_nome TEXT,
    "Qtd" TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the Truncate Function (if not already there or to ensure correct version)
CREATE OR REPLACE FUNCTION public.truncate_open_positions()
RETURNS void AS $$
BEGIN
    TRUNCATE TABLE public.open_positions;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.truncate_open_positions() TO anon;
GRANT EXECUTE ON FUNCTION public.truncate_open_positions() TO authenticated;

-- 3. Enable RLS and Configure Policies
ALTER TABLE public.open_positions ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to start fresh
DROP POLICY IF EXISTS "Enable all for everyone" ON public.open_positions;
DROP POLICY IF EXISTS "Enable select for everyone" ON public.open_positions;
DROP POLICY IF EXISTS "Enable insert for everyone" ON public.open_positions;
DROP POLICY IF EXISTS "Enable delete for everyone" ON public.open_positions;

-- Create unified policy (or separate ones for clarity)
-- This allows the app (anon) to see, add, and clear data.
CREATE POLICY "Enable select for everyone" ON public.open_positions FOR SELECT USING (true);
CREATE POLICY "Enable insert for everyone" ON public.open_positions FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable delete for everyone" ON public.open_positions FOR DELETE USING (true);

-- 4. Verify/Fix Encoding (Optional but recommended)
-- If data was imported with bad encoding, these policies won't fix it, 
-- but they will allow a new, clean import to work.
